const model = {
  app: {
    // app: document.getElementById("app"),
    adminLoggedIn: false,
    currentPage: "frontPage", // selectionPage, storeFrontPage, writeReviewPage, loginPage, adminPage,
    pages: ["frontPage", "selectionPage", "storeFrontPage", "writeReviewPage", "loginPage", "adminPage"],
    currentCity: 0,
    // currentUser: "",
  },

  viewState: {
    selectionPage: {
      storeType: "",
    },

    storeFrontPage: {
      selectedCity: 0,
      selectedStore: 0,
      adminReview: "",
      adminStore: "",
    },

    writeReviewPage: {
      userScore: 0,
      userReview: "",
      userName: "",
      userPicture: [],
    },

    loginPage: {
      username: "",
      userPassword: "",
      loginInvalid: "",
    },
  },

  // data
  data: {
    credentials: [
      {
        admin: {
          name: "anita",
          password: "anita",
        },
      },
    ],

    cities: [

      {   name: "Oslo",  
      
          store: 
          [
              {
                reviews: 
              [
                {
                  name: "Anna Hansen",
                  pictures: [],
                  score: 5,
                  reviewText: "Fantastisk kaffe og hyggelig atmosfære!",
                  date: "2026-02-14",
                  likes: 12,
                },
                {
                  name: "Jonas Berg",
                  pictures: [],
                  score: 4,
                  reviewText: "God cappuccino, men litt dyrt.",
                  date: "2026-02-10",
                  likes: 5,
                },
              ],
              
              info: 
              {
                city: "Oslo",
                storeName: "Nordlys Kafé",
                type: "cafe",
                pictures: ["media/cafeFolder/Cafe.jpg"],
                address: "Karl Johans gate 15",
                phone: 22334455,
                email: "kontakt@nordlyskafe.no",
                averageScore: 4.5,
                reviewAmount: 120,
                link: "https://nordlyskafe.no",
              },
            },

            {
            reviews: 
            [
              {
                name: "Maria Olsen",
                pictures: [],
                score: 5,
                reviewText: "Beste kanelboller i byen!",
                date: "2026-01-20",
                likes: 20,
              },
            ],
            
            info: 
            {
              city: "Oslo",
              storeName: "Fjell Bakeri",
              type: "bakery",
              pictures: ["media/cafeFolder/Cafe (1).jpg"],
              address: "Bryggen 8",
              phone: 55667788,
              email: "post@fjellbakeri.no",
              averageScore: 4.8,
              reviewAmount: 85,
              link: "https://fjellbakeri.no",
            },
          },

          {
            reviews: 
            [
              {
                name: "Erik Johansen",
                pictures: [],
                score: 3,
                reviewText: "Greit sted, men pizzaen var litt tørr.",
                date: "2026-03-01",
                likes: 2,
              },
              {
                name: "Lise Nilsen",
                pictures: [],
                score: 4,
                reviewText: "God service og hyggelig personale.",
                date: "2026-03-03",
                likes: 4,
              },
            ],
            
            info: 
            {
              city: "Oslo",
              storeName: "PizzaHjørnet",
              type: "restaurant",
              pictures: ["media/cafeFolder/Cafe (3).jpg"],
              address: "Munkegata 12",
              phone: 77889900,
              email: "hei@pizzahjornet.no",
              averageScore: 3.8,
              reviewAmount: 200,
              link: "https://pizzahjornet.no",
            },
          },

          {
            reviews: 
            [
              {
                name: "Sofie Larsen",
                pictures: [],
                score: 5,
                reviewText: "Utrolig gode kaker og flott presentasjon!",
                date: "2026-02-25",
                likes: 15,
              },
            ],
            
            info: 
            {
              city: "Oslo",
              storeName: "Arktisk Søtt",
              type: "bakery",
              pictures: ["media/cafeFolder/Cafe (2).jpg"],
              address: "Storgata 22",
              phone: 99887766,
              email: "kontakt@arktisksott.no",
              averageScore: 4.9,
              reviewAmount: 60,
              link: "https://arktisksott.no",
            },
          },
          
          {
            reviews: 
            [
              {
                name: "Daniel Pedersen",
                pictures: [],
                score: 4,
                reviewText: "Veldig bra burger og fries!",
                date: "2026-03-10",
                likes: 6,
              },
            ],
            
            info: 
            {
              city: "Oslo",
              storeName: "BurgerBua",
              type: "restaurant",
              pictures: ["media/cafeFolder/Cafe (5).jpg"],
              address: "Øvre Holmegate 5",
              phone: 66778899,
              email: "post@burgerbua.no",
              averageScore: 4.2,
              reviewAmount: 140,
              link: "https://burgerbua.no",
            },
          },
          
          {
            reviews: 
            [
              {
                name: "Henrik Solberg",
                pictures: [],
                score: 5,
                reviewText: "Perfekt sted for å jobbe og slappe av.",
                date: "2026-03-15",
                likes: 9,
              },
            ],
            
            info: 
            {
              city: "Oslo",
              storeName: "Nord Kaffe",
              type: "cafe",
              pictures: ["media/cafeFolder/Cafe (8).jpg"],
              address: "Markedsgata 3",
              phone: 11223344,
              email: "hei@nordkaffe.no",
              averageScore: 4.7,
              reviewAmount: 45,
              link: "https://nordkaffe.no",
            },
          },
        ], 
      },
      {   name:   "Bergen",
    
    
        store: [
          {
            reviews: [
              {
                name: "Maria L.",
                pictures: [],
                score: 5,
                reviewText: "Fantastiske boller og hyggelig personale!",
                date: "2026-02-12",
                likes: 3,
              },
              {
                name: "Jonas K.",
                pictures: [],
                score: 4,
                reviewText: "God kaffe, litt travelt.",
                date: "2026-01-20",
                likes: 1,
              },
              {
                name: "Ingrid S.",
                pictures: [],
                score: 5,
                reviewText: "Elsker croissantene her!",
                date: "2026-03-02",
                likes: 4,
              },
              {
                name: "Per H.",
                pictures: [],
                score: 4,
                reviewText: "Koselig sted og gode priser.",
                date: "2026-02-25",
                likes: 2,
              },
            ],
            info: {
              city: "Bergen",
              storeName: "Solglimt Bakeri",
              type: "bakery",
              pictures: ["media/cafeFolder/Cafe (7).jpg"],
              address: "Bryggen 12",
              phone: 55512345,
              email: "post@solglimt.no",
              averageScore: 4.5,
              reviewAmount: 4,
              link: "https://solglimt.no",
            },
          },

          {
            reviews: [
              {
                name: "Anne T.",
                pictures: [],
                score: 5,
                reviewText: "Beste cappuccino i byen.",
                date: "2026-03-01",
                likes: 5,
              },
              {
                name: "Lars E.",
                pictures: [],
                score: 4,
                reviewText: "Veldig bra atmosfære.",
                date: "2026-02-14",
                likes: 2,
              },
              {
                name: "Kari N.",
                pictures: [],
                score: 4,
                reviewText: "Hyggelig betjening.",
                date: "2026-01-30",
                likes: 1,
              },
              {
                name: "Ole M.",
                pictures: [],
                score: 5,
                reviewText: "Perfekt sted å jobbe fra.",
                date: "2026-02-18",
                likes: 3,
              },
            ],
            info: {
              city: "Bergen",
              storeName: "Fjellro Kafé",
              type: "cafe",
              pictures: ["media/cafeFolder/Cafe (9).jpg"],
              address: "Torgallmenningen 5",
              phone: 55567890,
              email: "hei@fjellro.no",
              averageScore: 4.5,
              reviewAmount: 4,
              link: "https://fjellro.no",
            },
          },

          {
            reviews: [
              {
                name: "Sofie B.",
                pictures: [],
                score: 5,
                reviewText: "Utrolig god pizza!",
                date: "2026-03-03",
                likes: 6,
              },
              {
                name: "Daniel W.",
                pictures: [],
                score: 4,
                reviewText: "God mat, litt lang ventetid.",
                date: "2026-02-27",
                likes: 2,
              },
              {
                name: "Emma R.",
                pictures: [],
                score: 5,
                reviewText: "Fantastisk service.",
                date: "2026-02-10",
                likes: 4,
              },
              {
                name: "Henrik J.",
                pictures: [],
                score: 4,
                reviewText: "Hyggelig atmosfære.",
                date: "2026-01-22",
                likes: 1,
              },
            ],
            info: {
              city: "Bergen",
              storeName: "Bryggen Restaurant",
              type: "restaurant",
              pictures: ["media/cafeFolder/Cafe (10).jpg"],
              address: "Bryggen 25",
              phone: 55511223,
              email: "booking@bryggenrest.no",
              averageScore: 4.5,
              reviewAmount: 4,
              link: "https://bryggenrest.no",
            },
          },

          {
            reviews: [
              {
                name: "Mats O.",
                pictures: [],
                score: 4,
                reviewText: "Veldig gode kaker.",
                date: "2026-02-05",
                likes: 2,
              },
              {
                name: "Elise V.",
                pictures: [],
                score: 5,
                reviewText: "Beste bakeriet i Bergen!",
                date: "2026-03-04",
                likes: 5,
              },
              {
                name: "Thomas G.",
                pictures: [],
                score: 4,
                reviewText: "God kvalitet, litt dyrt.",
                date: "2026-02-19",
                likes: 1,
              },
              {
                name: "Nora P.",
                pictures: [],
                score: 5,
                reviewText: "Elsker utvalget her.",
                date: "2026-01-28",
                likes: 3,
              },
            ],
            info: {
              city: "Bergen",
              storeName: "Bybakeriet",
              type: "bakery",
              pictures: ["media/cafeFolder/Cafe (11).jpg"],
              address: "Marken 8",
              phone: 55533445,
              email: "kontakt@bybakeriet.no",
              averageScore: 4.5,
              reviewAmount: 4,
              link: "https://bybakeriet.no",
            },
          },

          {
            reviews: [
              {
                name: "Fredrik L.",
                pictures: [],
                score: 5,
                reviewText: "Fantastisk burger!",
                date: "2026-03-06",
                likes: 4,
              },
              {
                name: "Sara D.",
                pictures: [],
                score: 4,
                reviewText: "God mat og hyggelig sted.",
                date: "2026-02-16",
                likes: 2,
              },
              {
                name: "Kristian F.",
                pictures: [],
                score: 4,
                reviewText: "Bra service.",
                date: "2026-01-19",
                likes: 1,
              },
              {
                name: "Julie A.",
                pictures: [],
                score: 5,
                reviewText: "Kommer definitivt tilbake.",
                date: "2026-02-28",
                likes: 3,
              },
            ],
            info: {
              city: "Bergen",
              storeName: "Vestkanten Grill",
              type: "restaurant",
              pictures: ["media/cafeFolder/Cafe (12).jpg"],
              address: "Vestkanten 3",
              phone: 55566778,
              email: "post@vestkantengrill.no",
              averageScore: 4.5,
              reviewAmount: 4,
              link: "https://vestkantengrill.no",
            },
          },
        ],

      }, 
      { name: "Trondheim",
      store: [
        {
          reviews: [
            {
              name: "Lars Nilsen",
              pictures: [],
              score: 5,
              reviewText: "Veldig koselig sted og god kaffe!",
              date: "2026-03-01",
              likes: 8,
            },
            {
              name: "Ingrid Solberg",
              pictures: [],
              score: 4,
              reviewText: "Hyggelig service, men litt travelt.",
              date: "2026-02-25",
              likes: 3,
            },
          ],
          info: {
            city: "Trondheim",
            storeName: "Fjord Kafé",
            type: "cafe",
            pictures: [],
            address: "Munkegata 10",
            phone: 73567890,
            email: "post@fjordkafe.no",
            averageScore: 4.3,
            reviewAmount: 58,
            link: "https://fjordkafe.no",
          },
        },

        {
          reviews: [
            {
              name: "Ole Johansen",
              pictures: [],
              score: 5,
              reviewText: "Beste bakverk i byen!",
              date: "2026-03-05",
              likes: 15,
            },
          ],
          info: {
            city: "Trondheim",
            storeName: "Bakst & Glede",
            type: "bakery",
            pictures: [],
            address: "Olav Tryggvasons gate 22",
            phone: 73881234,
            email: "hei@bakstoglede.no",
            averageScore: 4.8,
            reviewAmount: 210,
            link: "https://bakstoglede.no",
          },
        },

        {
          reviews: [],
          info: {
            city: "Trondheim",
            storeName: "Midtbyen Sushi",
            type: "restaurant",
            pictures: [],
            address: "Søndre gate 5",
            phone: 73990011,
            email: "kontakt@midtbyensushi.no",
            averageScore: 4.1,
            reviewAmount: 34,
            link: "https://midtbyensushi.no",
          },
        },

        {
          reviews: [
            {
              name: "Kari Olsen",
              pictures: [],
              score: 3,
              reviewText: "Greit nok, men kunne vært bedre utvalg.",
              date: "2026-02-20",
              likes: 2,
            },
            {
              name: "Per Hansen",
              pictures: [],
              score: 4,
              reviewText: "Bra kvalitet på klærne.",
              date: "2026-02-18",
              likes: 6,
            },
            {
              name: "Eva Lund",
              pictures: [],
              score: 5,
              reviewText: "Elsker denne butikken!",
              date: "2026-02-15",
              likes: 9,
            },
          ],
          info: {
            city: "Trondheim",
            storeName: "Trønder Stil",
            type: "clothing",
            pictures: [],
            address: "Nordregate 12",
            phone: 73551122,
            email: "info@tronderstil.no",
            averageScore: 4.4,
            reviewAmount: 89,
            link: "https://tronderstil.no",
          },
        },

        {
          reviews: [
            {
              name: "Mats Eriksen",
              pictures: [],
              score: 5,
              reviewText: "Fantastisk pizza!",
              date: "2026-03-02",
              likes: 11,
            },
          ],
          info: {
            city: "Trondheim",
            storeName: "PizzaHjørnet",
            type: "restaurant",
            pictures: [],
            address: "Kongens gate 30",
            phone: 73887766,
            email: "post@pizzahjornet.no",
            averageScore: 4.6,
            reviewAmount: 140,
            link: "https://pizzahjornet.no",
          },
        },

        {
          reviews: [
            {
              name: "Sofie Aas",
              pictures: [],
              score: 4,
              reviewText: "God kaffe, litt lite sitteplasser.",
              date: "2026-03-03",
              likes: 4,
            },
            {
              name: "Henrik Dahl",
              pictures: [],
              score: 5,
              reviewText: "Perfekt sted for studier.",
              date: "2026-03-01",
              likes: 7,
            },
          ],
          info: {
            city: "Trondheim",
            storeName: "Student Kaféen",
            type: "cafe",
            pictures: [],
            address: "Elgeseter gate 1",
            phone: 73559988,
            email: "kontakt@studentkafeen.no",
            averageScore: 4.5,
            reviewAmount: 76,
            link: "https://studentkafeen.no",
          },
        },

        {
          reviews: [],
          info: {
            city: "Trondheim",
            storeName: "TechHuset",
            type: "electronics",
            pictures: [],
            address: "Brattørgata 8",
            phone: 73880022,
            email: "support@techhuset.no",
            averageScore: 4.0,
            reviewAmount: 45,
            link: "https://techhuset.no",
          },
        },

        {
          reviews: [
            {
              name: "Daniel Vik",
              pictures: [],
              score: 5,
              reviewText: "Utrolig gode burgere!",
              date: "2026-03-06",
              likes: 13,
            },
            {
              name: "Ida Moe",
              pictures: [],
              score: 4,
              reviewText: "Saftig burger, men litt ventetid.",
              date: "2026-03-04",
              likes: 6,
            },
          ],
          info: {
            city: "Trondheim",
            storeName: "Burgerhjørnet",
            type: "restaurant",
            pictures: [],
            address: "Thomas Angells gate 14",
            phone: 73995544,
            email: "hei@burgerhjornet.no",
            averageScore: 4.7,
            reviewAmount: 165,
            link: "https://burgerhjornet.no",
          },
        },

        {
          reviews: [
            {
              name: "Nora Lie",
              pictures: [],
              score: 3,
              reviewText: "Helt greit, men litt dyrt.",
              date: "2026-02-28",
              likes: 2,
            },
          ],
          info: {
            city: "Trondheim",
            storeName: "Grønn Handel",
            type: "grocery",
            pictures: [],
            address: "Bakkegata 5",
            phone: 73553311,
            email: "post@gronhandel.no",
            averageScore: 3.9,
            reviewAmount: 52,
            link: "https://gronhandel.no",
          },
        },

        {
          reviews: [
            {
              name: "Erik Strand",
              pictures: [],
              score: 5,
              reviewText: "Beste kaffebønnene jeg har smakt!",
              date: "2026-03-07",
              likes: 10,
            },
            {
              name: "Maria Haug",
              pictures: [],
              score: 5,
              reviewText: "Fantastisk kvalitet og service.",
              date: "2026-03-05",
              likes: 8,
            },
            {
              name: "Thomas Bye",
              pictures: [],
              score: 4,
              reviewText: "Litt dyrt, men verdt det.",
              date: "2026-03-02",
              likes: 5,
            },
          ],
          info: {
            city: "Trondheim",
            storeName: "Kaffebrenneriet Trondheim",
            type: "cafe",
            pictures: [],
            address: "Nedre Bakklandet 20",
            phone: 73889977,
            email: "kontakt@kaffebrenneriet.no",
            averageScore: 4.8,
            reviewAmount: 198,
            link: "https://kaffebrenneriet.no",
          },
        },
      ],
      },
      { name: "Tromsø",
        store: [
                {
                  reviews: [
                    {
                      name: "Maja Olsen",
                      pictures: [],
                      score: 5,
                      reviewText: "Helt fantastisk kaffe og utsikt!",
                      date: "2026-03-10",
                      likes: 14,
                    },
                    {
                      name: "Henrik Johansen",
                      pictures: [],
                      score: 2,
                      reviewText: "Altfor dyrt for det du får.",
                      date: "2026-03-08",
                      likes: 3,
                    },
                    {
                      name: "Silje Nilsen",
                      pictures: [],
                      score: 4,
                      reviewText: "God stemning, men litt kaldt inne.",
                      date: "2026-03-06",
                      likes: 6,
                    },
                  ],
                  info: {
                    city: "Tromsø",
                    storeName: "Nordlys Kaffebar",
                    type: "cafe",
                    pictures: [],
                    address: "Storgata 22",
                    phone: 77665544,
                    email: "hei@nordlyskaffe.no",
                    averageScore: 3.9,
                    reviewAmount: 87,
                    link: "https://nordlyskaffe.no",
                  },
                },

                {
                  reviews: [
                    {
                      name: "Per Hansen",
                      pictures: [],
                      score: 1,
                      reviewText: "Dårlig service og kald mat.",
                      date: "2026-03-11",
                      likes: 9,
                    },
                    {
                      name: "Anna Berg",
                      pictures: [],
                      score: 3,
                      reviewText: "Helt ok, men ikke noe spesielt.",
                      date: "2026-03-09",
                      likes: 4,
                    },
                  ],
                  info: {
                    city: "Tromsø",
                    storeName: "Arktisk Bites",
                    type: "restaurant",
                    pictures: [],
                    address: "Grønnegata 10",
                    phone: 77889900,
                    email: "post@arktiskbites.no",
                    averageScore: 2.8,
                    reviewAmount: 54,
                    link: "https://arktiskbites.no",
                  },
                },

                {
                  reviews: [
                    {
                      name: "Lars Vik",
                      pictures: [],
                      score: 5,
                      reviewText: "Beste burgeren i Tromsø!",
                      date: "2026-03-12",
                      likes: 18,
                    },
                    {
                      name: "Ingrid Moe",
                      pictures: [],
                      score: 4,
                      reviewText: "Veldig god mat, litt lang ventetid.",
                      date: "2026-03-10",
                      likes: 7,
                    },
                    {
                      name: "Jonas Dahl",
                      pictures: [],
                      score: 3,
                      reviewText: "Bra, men ikke wow.",
                      date: "2026-03-08",
                      likes: 2,
                    },
                    {
                      name: "Kari Lie",
                      pictures: [],
                      score: 5,
                      reviewText: "Elsker dette stedet!",
                      date: "2026-03-07",
                      likes: 11,
                    },
                  ],
                  info: {
                    city: "Tromsø",
                    storeName: "Isbjørn Burger",
                    type: "restaurant",
                    pictures: [],
                    address: "Storgata 45",
                    phone: 77881122,
                    email: "hei@isbjornburger.no",
                    averageScore: 4.6,
                    reviewAmount: 143,
                    link: "https://isbjornburger.no",
                  },
                },

                {
                  reviews: [
                    {
                      name: "Eva Strand",
                      pictures: [],
                      score: 2,
                      reviewText: "Lite utvalg og høye priser.",
                      date: "2026-03-05",
                      likes: 5,
                    },
                  ],
                  info: {
                    city: "Tromsø",
                    storeName: "Nord Handel",
                    type: "grocery",
                    pictures: [],
                    address: "Langnesvegen 3",
                    phone: 77661234,
                    email: "post@nordhandel.no",
                    averageScore: 2.5,
                    reviewAmount: 31,
                    link: "https://nordhandel.no",
                  },
                },

                {
                  reviews: [
                    {
                      name: "Thomas Berg",
                      pictures: [],
                      score: 5,
                      reviewText: "Fantastisk atmosfære og gode drinker!",
                      date: "2026-03-12",
                      likes: 16,
                    },
                    {
                      name: "Nora Aas",
                      pictures: [],
                      score: 4,
                      reviewText: "Koselig sted, men litt høy musikk.",
                      date: "2026-03-10",
                      likes: 6,
                    },
                  ],
                  info: {
                    city: "Tromsø",
                    storeName: "Aurora Bar",
                    type: "bar",
                    pictures: [],
                    address: "Skippergata 12",
                    phone: 77887766,
                    email: "kontakt@aurorabar.no",
                    averageScore: 4.4,
                    reviewAmount: 98,
                    link: "https://aurorabar.no",
                  },
                },

                {
                  reviews: [
                    {
                      name: "Sofie Lund",
                      pictures: [],
                      score: 5,
                      reviewText: "Utrolig gode kaker!",
                      date: "2026-03-11",
                      likes: 12,
                    },
                    {
                      name: "Mats Eriksen",
                      pictures: [],
                      score: 4,
                      reviewText: "God smak, men litt dyrt.",
                      date: "2026-03-09",
                      likes: 4,
                    },
                    {
                      name: "Ida Hansen",
                      pictures: [],
                      score: 1,
                      reviewText: "Tørr kake og dårlig service.",
                      date: "2026-03-06",
                      likes: 7,
                    },
                  ],
                  info: {
                    city: "Tromsø",
                    storeName: "Søt Fristelse",
                    type: "bakery",
                    pictures: [],
                    address: "Storgata 8",
                    phone: 77885533,
                    email: "hei@sotfristelse.no",
                    averageScore: 3.3,
                    reviewAmount: 67,
                    link: "https://sotfristelse.no",
                  },
                },


                {
                  reviews: [
                    {
                      name: "Ole Pedersen",
                      pictures: [],
                      score: 4,
                      reviewText: "God sushi og hyggelig personale.",
                      date: "2026-03-11",
                      likes: 6,
                    },
                    {
                      name: "Kari Berg",
                      pictures: [],
                      score: 2,
                      reviewText: "Fisken var ikke fersk nok.",
                      date: "2026-03-09",
                      likes: 5,
                    },
                    {
                      name: "Lena Aas",
                      pictures: [],
                      score: 5,
                      reviewText: "Beste sushi i byen!",
                      date: "2026-03-07",
                      likes: 9,
                    },
                    {
                      name: "Jon Eriksen",
                      pictures: [],
                      score: 3,
                      reviewText: "Helt greit.",
                      date: "2026-03-05",
                      likes: 1,
                    },
                  ],
                  info: {
                    city: "Tromsø",
                    storeName: "Fjord Sushi",
                    type: "restaurant",
                    pictures: [],
                    address: "Grønnegata 25",
                    phone: 77882211,
                    email: "kontakt@fjordsushi.no",
                    averageScore: 3.6,
                    reviewAmount: 112,
                    link: "https://fjordsushi.no",
                  },
                },
              ], 
      },
      { name: "Stavanger",
      store: [
              {
                reviews: [
                  {
                    name: "Lars Nilsen",
                    pictures: [],
                    score: 5,
                    reviewText: "Kaffen var så god at jeg glemte å sjekke mobilen. Det skjer aldri.",
                    date: "2026-03-12",
                    likes: 19,
                  },
                  {
                    name: "Emma Berg",
                    pictures: [],
                    score: 2,
                    reviewText: "Bestilte latte, fikk noe som smakte som mandag morgen.",
                    date: "2026-03-10",
                    likes: 7,
                  },
                  {
                    name: "Jonas Moe",
                    pictures: [],
                    score: 4,
                    reviewText: "Veldig bra, men køen ga meg tid til å reflektere over livet.",
                    date: "2026-03-08",
                    likes: 6,
                  },
                ],
                info: {
                  city: "Stavanger",
                  storeName: "Kaffekroken",
                  type: "cafe",
                  pictures: [],
                  address: "Øvre Holmegate 10",
                  phone: 51881212,
                  email: "hei@kaffekroken.no",
                  averageScore: 3.9,
                  reviewAmount: 132,
                  link: "https://kaffekroken.no",
                },
              },

              {
                reviews: [
                  {
                    name: "Mia Hansen",
                    pictures: [],
                    score: 5,
                    reviewText: "Baksten var så god at jeg vurderte å gifte meg med en bolle.",
                    date: "2026-03-11",
                    likes: 25,
                  },
                  {
                    name: "Per Johansen",
                    pictures: [],
                    score: 3,
                    reviewText: "God smak, men jeg spiste for mye og skylder på dem.",
                    date: "2026-03-09",
                    likes: 10,
                  },
                ],
                info: {
                  city: "Stavanger",
                  storeName: "Bolle & Bønner",
                  type: "bakery",
                  pictures: [],
                  address: "Breigata 14",
                  phone: 51887755,
                  email: "post@bollebonner.no",
                  averageScore: 4.4,
                  reviewAmount: 210,
                  link: "https://bollebonner.no",
                },
              },

              {
                reviews: [],
                info: {
                  city: "Stavanger",
                  storeName: "HavSmak Restaurant",
                  type: "restaurant",
                  pictures: [],
                  address: "Skagenkaien 6",
                  phone: 51990022,
                  email: "kontakt@havsmak.no",
                  averageScore: 4.1,
                  reviewAmount: 45,
                  link: "https://havsmak.no",
                },
              },

              {
                reviews: [
                  {
                    name: "Kari Lie",
                    pictures: [],
                    score: 1,
                    reviewText: "Maten kom sent. Jeg rakk å bli eldre.",
                    date: "2026-03-07",
                    likes: 14,
                  },
                  {
                    name: "Ole Strand",
                    pictures: [],
                    score: 4,
                    reviewText: "God burger, men litt mye saus. Jeg svømmer fortsatt.",
                    date: "2026-03-06",
                    likes: 8,
                  },
                  {
                    name: "Nora Aas",
                    pictures: [],
                    score: 5,
                    reviewText: "Elsker dette stedet! Kom sulten, dro trillet ut.",
                    date: "2026-03-05",
                    likes: 12,
                  },
                ],
                info: {
                  city: "Stavanger",
                  storeName: "BurgerBrygga",
                  type: "restaurant",
                  pictures: [],
                  address: "Verksgata 9",
                  phone: 51776677,
                  email: "hei@burgerbrygga.no",
                  averageScore: 3.8,
                  reviewAmount: 167,
                  link: "https://burgerbrygga.no",
                },
              },

              {
                reviews: [
                  {
                    name: "Ida Moe",
                    pictures: [],
                    score: 5,
                    reviewText: "Smoothien ga meg energi og falsk tro på at jeg er sunn.",
                    date: "2026-03-12",
                    likes: 11,
                  },
                  {
                    name: "Henrik Vik",
                    pictures: [],
                    score: 2,
                    reviewText: "God, men jeg savnet noe å tygge på.",
                    date: "2026-03-10",
                    likes: 4,
                  },
                ],
                info: {
                  city: "Stavanger",
                  storeName: "Grønn Pause",
                  type: "cafe",
                  pictures: [],
                  address: "Nygata 5",
                  phone: 51883300,
                  email: "post@gronnpause.no",
                  averageScore: 3.6,
                  reviewAmount: 74,
                  link: "https://gronnpause.no",
                },
              },

              {
                reviews: [
                  {
                    name: "Sofie Berg",
                    pictures: [],
                    score: 4,
                    reviewText: "God pizza, men jeg brente tunga. Igjen.",
                    date: "2026-03-11",
                    likes: 6,
                  },
                  {
                    name: "Lars Hansen",
                    pictures: [],
                    score: 5,
                    reviewText: "Perfekt bunn og masse smak!",
                    date: "2026-03-09",
                    likes: 9,
                  },
                  {
                    name: "Jon Eriksen",
                    pictures: [],
                    score: 3,
                    reviewText: "Helt greit, men ikke revolusjonerende.",
                    date: "2026-03-08",
                    likes: 3,
                  },
                ],
                info: {
                  city: "Stavanger",
                  storeName: "Steinovn Pizza",
                  type: "restaurant",
                  pictures: [],
                  address: "Kirkegata 3",
                  phone: 51994411,
                  email: "hei@steinovnpizza.no",
                  averageScore: 4.0,
                  reviewAmount: 156,
                  link: "https://steinovnpizza.no",
                },
              },

              {
                reviews: [],
                info: {
                  city: "Stavanger",
                  storeName: "Søt Fristelse Stavanger",
                  type: "bakery",
                  pictures: [],
                  address: "Pedersgata 20",
                  phone: 51885522,
                  email: "kontakt@sotfristelse.no",
                  averageScore: 4.5,
                  reviewAmount: 98,
                  link: "https://sotfristelse.no",
                },
              },

              {
                reviews: [
                  {
                    name: "Thomas Aas",
                    pictures: [],
                    score: 2,
                    reviewText: "Fisken var god, men så på meg som om den visste noe.",
                    date: "2026-03-10",
                    likes: 10,
                  },
                  {
                    name: "Maria Lie",
                    pictures: [],
                    score: 5,
                    reviewText: "Beste sushi i byen!",
                    date: "2026-03-08",
                    likes: 13,
                  },
                  {
                    name: "Eva Strand",
                    pictures: [],
                    score: 4,
                    reviewText: "Veldig bra, men litt små biter.",
                    date: "2026-03-06",
                    likes: 5,
                  },
                ],
                info: {
                  city: "Stavanger",
                  storeName: "SushiHavna",
                  type: "restaurant",
                  pictures: [],
                  address: "Skippergata 4",
                  phone: 51993322,
                  email: "post@sushihavna.no",
                  averageScore: 3.9,
                  reviewAmount: 121,
                  link: "https://sushihavna.no",
                },
              },

              {
                reviews: [
                  {
                    name: "Ole Berg",
                    pictures: [],
                    score: 5,
                    reviewText: "Vaflene var så gode at jeg glemte hva jeg skulle gjøre etterpå.",
                    date: "2026-03-11",
                    likes: 15,
                  },
                  {
                    name: "Nora Hansen",
                    pictures: [],
                    score: 3,
                    reviewText: "God smak, men litt lite topping.",
                    date: "2026-03-09",
                    likes: 4,
                  },
                ],
                info: {
                  city: "Stavanger",
                  storeName: "Vaffelhjørnet",
                  type: "cafe",
                  pictures: [],
                  address: "Langgata 7",
                  phone: 51887788,
                  email: "hei@vaffelhjorne.no",
                  averageScore: 4.1,
                  reviewAmount: 83,
                  link: "https://vaffelhjorne.no",
                },
              },

              {
                reviews: [
                  {
                    name: "Henrik Moe",
                    pictures: [],
                    score: 1,
                    reviewText: "Pastaen var overkokt. Den hadde gitt opp før jeg gjorde det.",
                    date: "2026-03-08",
                    likes: 12,
                  },
                  {
                    name: "Lise Vik",
                    pictures: [],
                    score: 4,
                    reviewText: "God smak, men litt dyrt.",
                    date: "2026-03-07",
                    likes: 6,
                  },
                  {
                    name: "Kari Nilsen",
                    pictures: [],
                    score: 5,
                    reviewText: "Fantastisk pasta! Kommer tilbake.",
                    date: "2026-03-06",
                    likes: 9,
                  },
                ],
                info: {
                  city: "Stavanger",
                  storeName: "Pastahuset",
                  type: "restaurant",
                  pictures: [],
                  address: "Kongsgata 18",
                  phone: 51775500,
                  email: "kontakt@pastahuset.no",
                  averageScore: 3.7,
                  reviewAmount: 109,
                  link: "https://pastahuset.no",
                },
              },
            ],
      }, 
      { name: "Alta",
      store: [
              {
                reviews: [
                  {
                    name: "Ole Hansen",
                    pictures: [],
                    score: 5,
                    reviewText: "Kaffen var så sterk at jeg fortsatt er våken siden tirsdag.",
                    date: "2026-03-12",
                    likes: 16,
                  },
                  {
                    name: "Mia Berg",
                    pictures: [],
                    score: 3,
                    reviewText: "Koselig sted, men jeg frøs litt… eller det er kanskje bare Alta.",
                    date: "2026-03-10",
                    likes: 8,
                  },
                ],
                info: {
                  city: "Alta",
                  storeName: "Nordlys Kaffehus",
                  type: "cafe",
                  pictures: [],
                  address: "Markedsgata 12",
                  phone: 78451234,
                  email: "hei@nordlyskaffe.no",
                  averageScore: 4.1,
                  reviewAmount: 87,
                  link: "https://nordlyskaffe.no",
                },
              },

              {
                reviews: [
                  {
                    name: "Per Johansen",
                    pictures: [],
                    score: 1,
                    reviewText: "Pizzaen var kald. Jeg ble kald. Alt var kaldt.",
                    date: "2026-03-11",
                    likes: 12,
                  },
                  {
                    name: "Anna Nilsen",
                    pictures: [],
                    score: 4,
                    reviewText: "God smak, bare litt treg servering.",
                    date: "2026-03-09",
                    likes: 5,
                  },
                  {
                    name: "Jonas Vik",
                    pictures: [],
                    score: 5,
                    reviewText: "Elsker dette stedet! Kommer tilbake (med jakke).",
                    date: "2026-03-08",
                    likes: 9,
                  },
                ],
                info: {
                  city: "Alta",
                  storeName: "Arktisk Pizza",
                  type: "restaurant",
                  pictures: [],
                  address: "Altaveien 5",
                  phone: 78459876,
                  email: "post@arktiskpizza.no",
                  averageScore: 3.6,
                  reviewAmount: 143,
                  link: "https://arktiskpizza.no",
                },
              },

              {
                reviews: [],
                info: {
                  city: "Alta",
                  storeName: "Bakst & Kulde",
                  type: "bakery",
                  pictures: [],
                  address: "Løkkeveien 3",
                  phone: 78457788,
                  email: "kontakt@bakstkulde.no",
                  averageScore: 4.4,
                  reviewAmount: 52,
                  link: "https://bakstkulde.no",
                },
              },

              {
                reviews: [
                  {
                    name: "Kari Lie",
                    pictures: [],
                    score: 5,
                    reviewText: "Burgeren var så stor at jeg måtte ta pause halvveis.",
                    date: "2026-03-12",
                    likes: 14,
                  },
                  {
                    name: "Lars Strand",
                    pictures: [],
                    score: 2,
                    reviewText: "God burger, men fikk mer saus enn jeg fikk kontroll over livet mitt.",
                    date: "2026-03-10",
                    likes: 7,
                  },
                  {
                    name: "Nora Moe",
                    pictures: [],
                    score: 4,
                    reviewText: "Veldig bra, men litt rotete bord.",
                    date: "2026-03-09",
                    likes: 3,
                  },
                ],
                info: {
                  city: "Alta",
                  storeName: "BurgerBasen",
                  type: "restaurant",
                  pictures: [],
                  address: "Sentrumsgata 8",
                  phone: 78456677,
                  email: "hei@burgerbasen.no",
                  averageScore: 3.9,
                  reviewAmount: 119,
                  link: "https://burgerbasen.no",
                },
              },

              {
                reviews: [
                  {
                    name: "Emma Hansen",
                    pictures: [],
                    score: 5,
                    reviewText: "Kakene var så gode at jeg glemte nyttårsforsettet mitt.",
                    date: "2026-03-11",
                    likes: 18,
                  },
                  {
                    name: "Henrik Berg",
                    pictures: [],
                    score: 3,
                    reviewText: "Bra smak, men litt små porsjoner.",
                    date: "2026-03-09",
                    likes: 4,
                  },
                ],
                info: {
                  city: "Alta",
                  storeName: "Søt Nord",
                  type: "bakery",
                  pictures: [],
                  address: "Parkveien 2",
                  phone: 78459911,
                  email: "post@sotnord.no",
                  averageScore: 4.2,
                  reviewAmount: 76,
                  link: "https://sotnord.no",
                },
              },

              {
                reviews: [],
                info: {
                  city: "Alta",
                  storeName: "FjordSmak",
                  type: "restaurant",
                  pictures: [],
                  address: "Havneveien 6",
                  phone: 78452233,
                  email: "kontakt@fjordsmak.no",
                  averageScore: 4.0,
                  reviewAmount: 33,
                  link: "https://fjordsmak.no",
                },
              },

              {
                reviews: [
                  {
                    name: "Sofie Vik",
                    pictures: [],
                    score: 4,
                    reviewText: "God kaffe, men litt trangt lokale.",
                    date: "2026-03-10",
                    likes: 5,
                  },
                  {
                    name: "Daniel Aas",
                    pictures: [],
                    score: 1,
                    reviewText: "Bestilte te, fikk noe som smakte som varmt mysterium.",
                    date: "2026-03-08",
                    likes: 11,
                  },
                  {
                    name: "Mats Nilsen",
                    pictures: [],
                    score: 5,
                    reviewText: "Perfekt sted å varme seg etter kulda!",
                    date: "2026-03-07",
                    likes: 9,
                  },
                ],
                info: {
                  city: "Alta",
                  storeName: "Varm Kopp",
                  type: "cafe",
                  pictures: [],
                  address: "Torget 1",
                  phone: 78458899,
                  email: "hei@varmkopp.no",
                  averageScore: 3.8,
                  reviewAmount: 98,
                  link: "https://varmkopp.no",
                },
              },

              {
                reviews: [
                  {
                    name: "Ole Strand",
                    pictures: [],
                    score: 5,
                    reviewText: "Beste sushi jeg har hatt i nord!",
                    date: "2026-03-11",
                    likes: 13,
                  },
                  {
                    name: "Kari Berg",
                    pictures: [],
                    score: 2,
                    reviewText: "Fisken var ok, men risen var litt… kreativ.",
                    date: "2026-03-09",
                    likes: 6,
                  },
                  {
                    name: "Jon Moe",
                    pictures: [],
                    score: 3,
                    reviewText: "Helt greit, men ikke wow.",
                    date: "2026-03-07",
                    likes: 2,
                  },
                ],
                info: {
                  city: "Alta",
                  storeName: "Nord Sushi",
                  type: "restaurant",
                  pictures: [],
                  address: "Markedsgata 20",
                  phone: 78457700,
                  email: "post@nordsushi.no",
                  averageScore: 3.7,
                  reviewAmount: 111,
                  link: "https://nordsushi.no",
                },
              },

              {
                reviews: [],
                info: {
                  city: "Alta",
                  storeName: "Vaffelhjørnet Alta",
                  type: "cafe",
                  pictures: [],
                  address: "Elvebakken 4",
                  phone: 78453322,
                  email: "hei@vaffelalta.no",
                  averageScore: 4.3,
                  reviewAmount: 65,
                  link: "https://vaffelalta.no",
                },
              },

              {
                reviews: [
                  {
                    name: "Lise Moe",
                    pictures: [],
                    score: 1,
                    reviewText: "Pastaen var så myk at den ikke trengte tenner.",
                    date: "2026-03-08",
                    likes: 10,
                  },
                  {
                    name: "Per Vik",
                    pictures: [],
                    score: 4,
                    reviewText: "God smak, men litt dyrt.",
                    date: "2026-03-07",
                    likes: 4,
                  },
                  {
                    name: "Emma Lie",
                    pictures: [],
                    score: 5,
                    reviewText: "Fantastisk middag! Kommer igjen.",
                    date: "2026-03-06",
                    likes: 7,
                  },
                ],
                info: {
                  city: "Alta",
                  storeName: "Pastahuset Nord",
                  type: "restaurant",
                  pictures: [],
                  address: "Sentrum 15",
                  phone: 78456611,
                  email: "kontakt@pastahusetnord.no",
                  averageScore: 3.8,
                  reviewAmount: 124,
                  link: "https://pastahusetnord.no",
                },
              },
            ],
      }, 
    ],
  },
};





